TYPE=VIEW
query=select distinct `_lnkdocumenttosoftware`.`id` AS `id`,`_lnkdocumenttosoftware`.`software_id` AS `software_id`,`Software_software_id_software`.`name` AS `software_name`,`_lnkdocumenttosoftware`.`document_id` AS `document_id`,`Document_document_id_document`.`name` AS `document_name`,cast(concat(coalesce(`_lnkdocumenttosoftware`.`software_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkdocumenttosoftware`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Software_software_id_software`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`Software_software_id_software`.`version`,\'\')) as char charset utf8mb4) AS `software_id_friendlyname`,if((`Document_document_id_document`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id_document`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id_document`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id_document`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`mysql`.`lnkdocumenttosoftware` `_lnkdocumenttosoftware` join `mysql`.`software` `Software_software_id_software` on((`_lnkdocumenttosoftware`.`software_id` = `Software_software_id_software`.`id`))) join `mysql`.`document` `Document_document_id_document` on((`_lnkdocumenttosoftware`.`document_id` = `Document_document_id_document`.`id`))) where 1
md5=59a9058d9212b455a1265b8ffc6378ec
updatable=0
algorithm=0
definer_user=admin
definer_host=%
suid=2
with_check_option=0
timestamp=2019-02-01 19:02:22
create-version=2
source=SELECT DISTINCT `_lnkdocumenttosoftware`.`id` AS `id`, `_lnkdocumenttosoftware`.`software_id` AS `software_id`, `Software_software_id_software`.`name` AS `software_name`, `_lnkdocumenttosoftware`.`document_id` AS `document_id`, `Document_document_id_document`.`name` AS `document_name`, CAST(CONCAT(COALESCE(`_lnkdocumenttosoftware`.`software_id`, \'\'), COALESCE(\' \', \'\'), COALESCE(`_lnkdocumenttosoftware`.`document_id`, \'\')) AS CHAR) AS `friendlyname`, CAST(CONCAT(COALESCE(`Software_software_id_software`.`name`, \'\'), COALESCE(\' \', \'\'), COALESCE(`Software_software_id_software`.`version`, \'\')) AS CHAR) AS `software_id_friendlyname`, IF((`Document_document_id_document`.`finalclass` IN (\'Document\')), CAST(CONCAT(COALESCE(\'Document\', \'\')) AS CHAR), CAST(CONCAT(COALESCE(`Document_document_id_document`.`name`, \'\')) AS CHAR)) AS `document_id_friendlyname`, `Document_document_id_document`.`finalclass` AS `document_id_finalclass_recall`, COALESCE((`Document_document_id_document`.`status` = \'obsolete\'), 0) AS `document_id_obsolescence_flag` FROM `lnkdocumenttosoftware` AS `_lnkdocumenttosoftware`INNER JOIN `software` AS `Software_software_id_software` ON `_lnkdocumenttosoftware`.`software_id` = `Software_software_id_software`.`id`INNER JOIN `document` AS `Document_document_id_document` ON `_lnkdocumenttosoftware`.`document_id` = `Document_document_id_document`.`id` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_lnkdocumenttosoftware`.`id` AS `id`,`_lnkdocumenttosoftware`.`software_id` AS `software_id`,`Software_software_id_software`.`name` AS `software_name`,`_lnkdocumenttosoftware`.`document_id` AS `document_id`,`Document_document_id_document`.`name` AS `document_name`,cast(concat(coalesce(`_lnkdocumenttosoftware`.`software_id`,\'\'),coalesce(\' \',\'\'),coalesce(`_lnkdocumenttosoftware`.`document_id`,\'\')) as char charset utf8mb4) AS `friendlyname`,cast(concat(coalesce(`Software_software_id_software`.`name`,\'\'),coalesce(\' \',\'\'),coalesce(`Software_software_id_software`.`version`,\'\')) as char charset utf8mb4) AS `software_id_friendlyname`,if((`Document_document_id_document`.`finalclass` = \'Document\'),cast(concat(coalesce(\'Document\',\'\')) as char charset utf8mb4),cast(concat(coalesce(`Document_document_id_document`.`name`,\'\')) as char charset utf8mb4)) AS `document_id_friendlyname`,`Document_document_id_document`.`finalclass` AS `document_id_finalclass_recall`,coalesce((`Document_document_id_document`.`status` = \'obsolete\'),0) AS `document_id_obsolescence_flag` from ((`mysql`.`lnkdocumenttosoftware` `_lnkdocumenttosoftware` join `mysql`.`software` `Software_software_id_software` on((`_lnkdocumenttosoftware`.`software_id` = `Software_software_id_software`.`id`))) join `mysql`.`document` `Document_document_id_document` on((`_lnkdocumenttosoftware`.`document_id` = `Document_document_id_document`.`id`))) where 1
mariadb-version=100036
