TYPE=VIEW
query=select distinct `_faqcategory`.`id` AS `id`,`_faqcategory`.`nam` AS `name`,cast(concat(coalesce(`_faqcategory`.`nam`,\'\')) as char charset utf8mb4) AS `friendlyname` from `mysql`.`faqcategory` `_faqcategory` where 1
md5=55cdc3512fda6dfa98d32e0a07890644
updatable=0
algorithm=0
definer_user=admin
definer_host=%
suid=2
with_check_option=0
timestamp=2019-02-01 19:02:22
create-version=2
source=SELECT DISTINCT `_faqcategory`.`id` AS `id`, `_faqcategory`.`nam` AS `name`, CAST(CONCAT(COALESCE(`_faqcategory`.`nam`, \'\')) AS CHAR) AS `friendlyname` FROM `faqcategory` AS `_faqcategory` WHERE 1
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `_faqcategory`.`id` AS `id`,`_faqcategory`.`nam` AS `name`,cast(concat(coalesce(`_faqcategory`.`nam`,\'\')) as char charset utf8mb4) AS `friendlyname` from `mysql`.`faqcategory` `_faqcategory` where 1
mariadb-version=100036
